---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

name: '🛠️ Semantic Pull Request'

# yamllint disable-line rule:truthy
on:
  # Not supported when workflow contains: amannn/action-semantic-pull-request
  # workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pull-request:
    name: 'Semantic Pull Request'
    permissions:
      contents: read
      pull-requests: read
    # Testing the new reusable workflow from the fork prior to upstream
    # release; repoint to lfit/releng-reusable-workflows@<SHA> once merged.
    # yamllint disable-line rule:line-length
    uses: modeseven-lfit/releng-reusable-workflows/.github/workflows/reuse-semantic-pull-request.yaml@0d054aec887046ff43fc4707fd067dfd67b65a4d  # feat/reuse-semantic-pull-request
